version: '3.3'

services:

  terraling-dockerized-mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db/terraling_backup.sql:/docker-entrypoint-initdb.d/terraling_backup.sql
    environment:
      MYSQL_ROOT_PASSWORD: Terraling1!
      MYSQL_DATABASE: terraling_production
    expose:
      - '3306'

  terraling-dockerized:
    build: .
    image: terraling-dockerized
    restart: always
    volumes:
      - .:/terraling/
    ports:
      - "3001:3000"
    depends_on:
      - terraling-dockerized-mysql
